spring.application.name=agendaSpring
spring.datasource.url=jdbc:mysql://localhost/bdagenda
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:12345678}
server.port=8082
